### ISSUE TITLE
Update StyleCop plugin to ReSharper 2021.3 release version

### ISSUE THREAD

**Issue by AngieEl** [StyleCop/StyleCop.ReSharper#50]
ReShaper code analysis becomes disabled with the installed StyleCop 2021.3.0-eap7 version. There's a bunch of exceptions in the log:

```
13:30:24.647 |I| AddVsVersionToLogs            | :1                 | JetBrains ReSharper 2021.3 Build 213.0.20211207.74952
13:30:24.654 |I| AddVsVersionToLogs            | :1                 | Running in Visual Studio Professional 2022, Version 17.0.2 (17.0.31919.166), Hive: 17.0_328e9ea2
13:30:24.660 |I| AddVsVersionToLogs            | :1                 | Running on Windows 10 Pro 20H2, build 19042.1348, Professional, Client (Microsoft Windows NT 10.0.19042.0)
13:30:27.447 |I| DpaProtocolServerConnector    | :1                 | Starting frontend
13:30:27.463 |I| DpaProtocolServerConnector    | :1                 | Server created at 52157 port
13:30:27.465 |I| DpaProtocolServerConnector    | :1                 | Running backend from C:\Users\Angelina.Elycheva\AppData\Local\JetBrains\Installations\ReSharperPlatformVs17_328e9ea2\JetBrains.DPA.Ide.VS.Backend.exe at 127.0.0.1:52157 IsInternal:False
13:30:27.466 |I| LogFilesProviderComponent     | :1                 | log file: C:\Users\Angelina.Elycheva\AppData\Local\Temp\JetLogs\JetBrainsLog.JetBrains.2021-12-09T13-29-59.devenv#32732-DPA.Backend.log
13:30:33.265 |I| VsSolutionManager15           | :1                 | VSSolutionManager::OnAfterOpenSolution
13:30:41.147 |W| VsReSharperMainMenuFixesSinceVs16| :1                 | ReSharper menu is not found in the main VS menu.
13:30:41.354 |E| AsyncDescriptorBase           | :1                 | Component StyleCop.ReSharper.Options.HighlightingRegistering construction has failed Exception has been thrown by the target of an invocation. Method not found: 'Void JetBrains.ReSharper.Feature.Services.Daemon.ConfigurableSeverityItem..ctor(System.String, System.String, System.String, System.String, System.String, JetBrains.ReSharper.Feature.Services.Daemon.Severity, Boolean, Boolean, System.String, System.String, System.String)'.

--- EXCEPTION #1/3 [MissingMethodException]
Message = “Method not found: 'Void JetBrains.ReSharper.Feature.Services.Daemon.ConfigurableSeverityItem..ctor(System.String, System.String, System.String, System.String, System.String, JetBrains.ReSharper.Feature.Services.Daemon.Severity, Boolean, Boolean, System.String, System.String, System.String)'.”
ExceptionPath = Root.InnerException.InnerException
ClassName = System.MissingMethodException
Data.ThreadLocalDebugInfo = “DelayedInitializationStrategy.Dispatch: JetBrains.ReSharper.Psi.impl.EditorConfig.EditorConfigService”
HResult = COR_E_MISSINGMETHOD=80131513
Source = StyleCop.StyleCop
StackTraceString = “
  at StyleCop.ReSharper.Options.HighlightingRegistering.Register(StyleCopCore core)
     at StyleCop.ReSharper.Options.HighlightingRegistering.<>c__DisplayClass2_0.<.ctor>b__0(Lifetime temporaryLifetime) in Z:\buildAgent\work\fc1bcfed6a14b2e5\src\dotnet\StyleCop.StyleCop\Options\HighlightingRegistering.cs:line 74
     at JetBrains.Lifetimes.Lifetime.Using(Action`1 action)
”

--- Outer ---

--- EXCEPTION #2/3 [TargetInvocationException]
Message = “Exception has been thrown by the target of an invocation.”
ExceptionPath = Root.InnerException
ClassName = System.Reflection.TargetInvocationException
Data.ThreadLocalDebugInfo = “DelayedInitializationStrategy.Dispatch: JetBrains.ReSharper.Psi.impl.EditorConfig.EditorConfigService”
InnerException = “Exception #1 at Root.InnerException.InnerException”
HResult = COR_E_TARGETINVOCATION=80131604
Source = mscorlib
StackTraceString = “
  at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
     at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
     at JetBrains.Application.Components.ConstructiorBindigns.Activate(ISingletonDescriptor descriptor, Object[] dependencies)
     at JetBrains.Application.Components.SingletonDescriptor`1.CreateInstance(Object[] dependencies)
     at JetBrains.Application.Components.AsyncDescriptorBase.ActivatingComponentState.TryGetSyncImpl()
”

--- Outer ---

--- EXCEPTION #3/3 [LoggerException]
Message = “Component StyleCop.ReSharper.Options.HighlightingRegistering construction has failed Exception has been thrown by the target of an invocation.”
ExceptionPath = Root
ClassName = JetBrains.Util.LoggerException
Data.ManagedThreadName = <NULL>
InnerException = “Exception #2 at Root.InnerException”
HResult = COR_E_APPLICATION=80131600
StackTraceString = “
  at JetBrains.Util.ILoggerEx.LogException(ILogger this, LoggingLevel level, Exception exception, ExceptionOrigin exceptionOrigin, String comment)
     at JetBrains.Util.ILoggerEx.Error(ILogger this, Exception ex, String message)
     at JetBrains.Application.Components.AsyncDescriptorBase.SetCorruptedState(Exception e)
     at JetBrains.Application.Components.AsyncDescriptorBase.ActivatingComponentState.TryGetSyncImpl()
     at JetBrains.Application.Components.AsyncDescriptorBase.StateWithPriorityCache`1.TryGetSync()
     at JetBrains.Application.Components.AsyncDescriptorBase.TryActivate(Object[] dependencyValues)
     at JetBrains.Application.Components.AsyncDescriptorBase.TryGetOrCreateValue()
     at JetBrains.Application.Components.AsyncDescriptorBase.InitializingDependenciesComponentState.TryGetSyncUnsafe()
     at JetBrains.Application.Components.AsyncDescriptorBase.InitializingDependenciesComponentState.TryGetSyncImpl()
     at JetBrains.Application.Components.AsyncDescriptorBase.StateWithPriorityCache`1.TryGetSync()
     at JetBrains.Application.Components.AsyncDescriptorBase.TryGetDependencyValues()
     at JetBrains.Application.Components.AsyncDescriptorBase.TryGetOrCreateValue()
     at JetBrains.Application.Components.AsyncDescriptorBase.GetValue()
     at JetBrains.Application.Components.ComponentContainerEx.GetComponents[TInterface](IComponentContainer container)
     at JetBrains.ReSharper.Feature.Services.Daemon.HighlightingSettingsManagerImpl..ctor(Lifetime lifetime, ShellPartCatalogSet partsCatalogueSet, ILanguages allLanguages, ISettingsStore settingsStore, SettingsCacheManager cacheManger, ILogger logger, HighlightingDefaultSettingValuesProvider defaultSettingValuesProvider, ICalculatedSettingsSchema calculatedSettingsSchema)
     at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
     at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
     at JetBrains.Application.Components.ConstructiorBindigns.Activate(ISingletonDescriptor descriptor, Object[] dependencies)
     at JetBrains.Application.Components.SingletonDescriptor`1.CreateInstance(Object[] dependencies)
     at JetBrains.Application.Components.AsyncDescriptorBase.ActivatingComponentState.CreateInstanceWithReadLock()
     at JetBrains.Application.Components.AsyncDescriptorBase.ActivatingComponentState.TryGetSyncImpl()
     at JetBrains.Application.Components.AsyncDescriptorBase.StateWithPriorityCache`1.TryGetSync()
     at JetBrains.Application.Components.AsyncDescriptorBase.TryActivate(Object[] dependencyValues)
     at JetBrains.Application.Components.AsyncDescriptorBase.TryGetOrCreateValue()
     at JetBrains.Application.Components.AsyncDescriptorBase.InitializingDependenciesComponentState.TryGetSyncUnsafe()
     at JetBrains.Application.Components.AsyncDescriptorBase.InitializingDependenciesComponentState.TryGetSyncImpl()
     at JetBrains.Application.Components.AsyncDescriptorBase.StateWithPriorityCache`1.TryGetSync()
     at JetBrains.Application.Components.AsyncDescriptorBase.TryGetDependencyValues()
     at JetBrains.Application.Components.AsyncDescriptorBase.TryGetOrCreateValue()
     at JetBrains.Application.Components.AsyncDescriptorBase.InitializingDependenciesComponentState.TryGetSyncUnsafe()
     at JetBrains.Application.Components.AsyncDescriptorBase.InitializingDependenciesComponentState.TryGetSyncImpl()
     at JetBrains.Application.Components.AsyncDescriptorBase.StateWithPriorityCache`1.TryGetSync()
     at JetBrains.Application.Components.AsyncDescriptorBase.TryGetDependencyValues()
     at JetBrains.Application.Components.AsyncDescriptorBase.TryGetOrCreateValue()
     at JetBrains.Application.Components.AsyncDescriptorBase.InitializingDependenciesComponentState.TryGetSyncUnsafe()
     at JetBrains.Application.Components.AsyncDescriptorBase.InitializingDependenciesComponentState.TryGetSyncImpl()
     at JetBrains.Application.Components.AsyncDescriptorBase.StateWithPriorityCache`1.TryGetSync()
     at JetBrains.Application.Components.AsyncDescriptorBase.TryGetDependencyValues()
     at JetBrains.Application.Components.AsyncDescriptorBase.TryGetOrCreateValue()
     at JetBrains.Application.Components.AsyncDescriptorBase.InitializingDependenciesComponentState.TryGetSyncUnsafe()
     at JetBrains.Application.Components.AsyncDescriptorBase.InitializingDependenciesComponentState.TryGetSyncImpl()
     at JetBrains.Application.Components.AsyncDescriptorBase.StateWithPriorityCache`1.TryGetSync()
     at JetBrains.Application.Components.AsyncDescriptorBase.TryGetDependencyValues()
     at JetBrains.Application.Components.AsyncDescriptorBase.TryGetOrCreateValue()
     at JetBrains.Application.Components.AsyncDescriptorBase.GetValue()
     at JetBrains.Application.Components.DelayedInitializationStrategy.<Dispatch>b__8_1()
     at JetBrains.Util.Concurrency.ExecutionContextEx.<>c__DisplayClass0_0.<Run>b__0(Object _)
     at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
     at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
     at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
     at JetBrains.Util.Concurrency.ExecutionContextEx.Run(ExecutionContext context, ContextCallback callback, Object state)
     at JetBrains.Threading.ReentrancyGuard.Execute(String name, Action action)
     at JetBrains.Threading.ReentrancyGuard.ExecutePendingActions()
     at JetBrains.Util.Concurrency.ExecutionContextEx.<>c__DisplayClass0_0.<Run>b__0(Object _)
     at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
     at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
     at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
     at JetBrains.Util.Concurrency.ExecutionContextEx.Run(ExecutionContext context, ContextCallback callback, Object state)
     at JetBrains.Threading.JetDispatcher.Closure.Execute()
     at JetBrains.Util.Concurrency.WinJetDispatcher.ProcessQueue(Int32 nMinBucket)
     at JetBrains.Util.Concurrency.WinJetDispatcher.ExternalIdleProcessing.OnExternalDriverIdle()
     at JetBrains.VsIntegration.Shell.VsDoIdleDispatcherSink.Microsoft.VisualStudio.OLE.Interop.IOleComponent.FDoIdle(UInt32 grfidlef)
”

13:30:43.225 |E| AsyncDescriptorBase           | :1                 | Component JetBrains.ReSharper.Feature.Services.EditorConfig.EditorConfigHighlightingConverter construction has failed Exception has been thrown by the target of an invocation. Object reference not set to an instance of an object.

```

**Comment by AngieEl** [comment]
2021.3 is already available in the market.
